### ISSUE TITLE
Ever Increase App Size

### ISSUE THREAD

**Issue by theintel** [via-browser/Via#102]
The ultra light browser Via is awesome. And I love this specific browser even more than Chrome.

The issue that I've been experiencing lately is that the app size increases as I browse, and it keeps increasing. I tried cleaning everything with the options in the settings, no good news though. The 900kB app data reaches 16 + MB within 4 days and keeps increasing.

Is it normal? Can you suggest anything helpful to keep the size as less as possible?

**Comment by Vv2233Bb** [comment]
Are you talking about app data or about full size?(If it's full size it's probably just cache.

**Comment by theintel** [comment]
No no, I clean cache once in a while. Via has problem with cleaning browsing data, like not clearing images loaded from pages after exit.
I'm rooted and loking at /data/data/mark.via.go it seems like the app_webview directory gets populated with unnecessary stuff. Thus a 1.5MB app reaches 10MB in size and keeps increasing.

**Comment by Vv2233Bb** [comment]
Well for me app size is 1.5 MB, user data takes 2.8 and cache 19.8.

**Comment by tuyafeng** [comment]
Clear the cache every day, or turn on clear the cache when exit in settings.

**Comment by theintel** [comment]
> Clear the cache every day, or turn on clear the cache when exit in settings.

Tried that. Still it can't clear the cache reliably 😑
