### ISSUE TITLE
memory and battery issue

### ISSUE THREAD

**Issue by shellbombs** [via-browser/Via#109]
i like this little browser very much, but i found two issues.
1. the memory increase dramatically as time increase.
2. after close the browser, the browser's background processes still use battery heavily.

**Comment by skyformat99** [comment]
确实是这样啊
打开tab多了之后，内存增加不少。
感觉有泄露

**Comment by kucingmeong** [comment]
1. what do you mean by "memory"?

(link to imgur page)
1. https://goo.gl/mwSdtm
or
2. https://goo.gl/XrFBCJ
=======================
2. Just close via manually then
(settings-app-downloaded-via-force stop)
or "automatically"(example: greenify app)

**Comment by kucingmeong** [comment]
3. is 2. sorry

**Comment by tuyafeng** [comment]
Those bugs already have been fixed.
