### ISSUE TITLE
百度系网站和经过百度搜索跳转的网站会不停加载

### ISSUE THREAD

**Issue by forevergoagent** [via-browser/Via#110]
百度系网站和经过百度搜索跳转的网站会不停加载，进度条不停地闪，用自带浏览器没问题

**Comment by Xiaopika** [comment]
对对对，这个问题困扰我很久了，是由于百度有个防屏蔽的二次加载广告的脚本。目前解决办法是使用自己建的首页+简版百度。
http://xiaopika.gitee.io/page

**Comment by Xiaopika** [comment]
加载就算了其实也没问题，但是每次都会打断我的输入状态就很烦

**Comment by tuyafeng** [comment]
已解决。
