### ISSUE TITLE
建议，选中文本后弹出的工具条增加【链接打开】项

### ISSUE THREAD

**Issue by skyformat99** [via-browser/Via#111]
当在页面选中文本后，会弹出选项，比如
粘贴，复制，页面搜索之类的。
希望增加一个打开链接的项。

原因:  有时候读网页的时候，上面有一些链接，这个连接有时候是单纯的文本。
选中后，不能快速打开。

**Comment by tuyafeng** [comment]
长按菜单并不能定义，但是好在安卓目前已经加入了这个特性。
