### ISSUE TITLE
能否增强一下主页展示书签的自定义功能

### ISSUE THREAD

**Issue by 1016797313** [via-browser/Via#112]
via主页显示书签是按照书签的顺序来排的，但是这样很难控制你想要显示的书签。文件夹里的书签会显示在最前面。
能否把主页展示的书签(像其他浏览器的快速访问功能)和书签页面里的分离，可以单独设置，不是按照书签的顺序来排列

**Comment by Xiaopika** [comment]
history:/
在书签页可以长按每一个书签标题左边的书签图标拖动排序

**Comment by tuyafeng** [comment]
已支持直接添加书签到主页。
