### ISSUE TITLE
Add a feature to disable navigation bar colors

### ISSUE THREAD

**Issue by kairusds** [via-browser/Via#122]
Is this feature possible?

**Comment by Vv2233Bb** [comment]
Are you looking for Settings>General>Color mode?

**Comment by kairusds** [comment]
@Vv2233Bb nope, I was looking for a feature to DISABLE the colors on the navbar including the white color

**Comment by GiovanniCarrozza** [comment]
I agree with this request; personaly I like the navigation bars to be always black.

**Comment by tuyafeng** [comment]
The navigation bar of android is also changing, now it is a small thin line, it will be very strange if it is black.
