### ISSUE TITLE
Bugs and recomendations...

### ISSUE THREAD

**Issue by mire000** [via-browser/Via#128]
First i must say that this is best browser! So small, smooth, fast, uses less ram, and it is highly customizable.. 

I only found one bug..
And i have some recommendations..

Bug:

-Gesture for home button in simple UI mode (bottom mode), doesnt work!

Recommendations:

1) User should be abble to set 'custom text size'.

Because if i sellect predefined 'large' text from menu, this doesnt work well for all sites.

Example, this doesnt work well for youtube. Youtube text is cropped. I need something between large and normal.

2) Users should be abble to 'turn java off based on url', because some sites are 2 invasive on java scripts..

You can add button in menu - "turn java off for this site", and when user next time visit same site, java will be turned off..

3) You need option in menu: "add to speed dial".

You want quick acess to that function if you are on some site you like.

4) Search box on home page should not be empty. It should have text: "Search Google..." if Google is provider, or other provider if other is...

5) You should implement some data saving metod if that's possible..

Thank you for all your work!

**Comment by tuyafeng** [comment]
Sorry for replying so late. The bug has been fixed.

As for your recommendations:
1. I will think about it.
2. After version 3.9.8, you can set it at any time by clicking the icon on the left side of the URL bar(Site conf).
3. Already exists.
4. I think the blank looks better.
5. Ad blocking can save your data.
