### ISSUE TITLE
#NewFeatureRequest "Import/Export History"

### ISSUE THREAD

**Issue by kucingmeong** [via-browser/Via#131]
Sometimes we need to export our browser history to a single file for backup purpose
and the name will be "Via_HistoryExport_[date here]"  
(just like bookmark)

which is so useful for us (via user)

Thanks for your attention to click on this issue :)

**Comment by tuyafeng** [comment]
I think history is just a record of browsing. If it is really worth recording, I suggest you add it to bookmark.
