### ISSUE TITLE
#NewFeatureRequest "multi selection for history and bookmarks tab"

### ISSUE THREAD

**Issue by kucingmeong** [via-browser/Via#132]
this feature is so useful to remove some history record that we do not want to see on our history and bookmark list

for example: deloton, or other advertisement websites

example: (in file manager)
https://i.imgur.com/d27WuKq.png

Thanks for your attention :)

**Comment by tuyafeng** [comment]
The current bookmark history page is not perfect, and this part will be redesigned later.
