### ISSUE TITLE
用谷歌账号登录 stackedit.io 时有问题

### ISSUE THREAD

**Issue by Yves0** [via-browser/Via#135]
使用默认 UA 时 403 无法认证。更改 PC chrome 登录之后无法跳转回 stackedit.io。
用 chrome 登录没有问题

**Comment by tuyafeng** [comment]
时隔久远，不确定这个问题现在是否可以复现。看描述或许是网络连接不稳定？我先关闭 issue 了，如果仍有疑问欢迎随时开启。
