### ISSUE TITLE
Tabs and ease of access

### ISSUE THREAD

**Issue by DoggoOfSpeed** [via-browser/Via#140]
Hi. It would be very nice if the page would blur out after opening the place where you go between tabs so it would be easier to see opened tabs. This could be an option in settings>ease of access (Hopefully you will create this section:)). To fill it up (ease of access section) you could add an option to disable all transparency effects.
![screenshot_20180218-165156](https://user-images.githubusercontent.com/28051112/36353357-566809e8-14ce-11e8-97ed-c662926b858d.png)
<img width="540" alt="screenshot_20180218-165926fvfdvd" src="https://user-images.githubusercontent.com/28051112/36353358-56a249d2-14ce-11e8-831b-56bc4fff4809.png">

**Comment by tuyafeng** [comment]
The blur effect is very cool, but it also consumes resources. At present, all attempts are to speed up as much as possible (whether it is web page loading or application experience). In terms of performance and interface, I prefer the former.
