### ISSUE TITLE
Add Custom CSS

### ISSUE THREAD

**Issue by neerajtheblogger** [via-browser/Via#141]
Hi, How can I add custom css to it and add shortcuts on the homepage itself. Till now what I have explored is that I can only set margin of logo and nothing else please include the and tell your users how can they customize it more and make the process easier. May be I can help you out.

**Comment by aXeSoul5** [comment]
please do Answer

**Comment by tuyafeng** [comment]
Sorry for reply so late. In the next version(3.9.9), you can directly view the source code of the homepage (android5.0 +), then you can more easily see the relationship between the elements.
