### ISSUE TITLE
History is unorganized

### ISSUE THREAD

**Issue by DoggoOfSpeed** [via-browser/Via#145]
The history tab looks unorganized and messy. Maybe you could make it look more like this:
![untitled](https://user-images.githubusercontent.com/28051112/37303816-4a355e5c-2638-11e8-8e8a-00d045e1f7e5.png)

**Comment by Vv2233Bb** [comment]
History tab should have its own settings menu.

**Comment by Vv2233Bb** [comment]
Or it could look like this:
![reallone](https://user-images.githubusercontent.com/28051112/37597773-081e9b68-2b89-11e8-8b0c-b064fbd334f9.png)
It would be separated in folders. It is similar to other browsers but it looks good.

**Comment by tuyafeng** [comment]
Thank you for your suggestion, I will consider it.
