### ISSUE TITLE
In-app icons are inconsistent

### ISSUE THREAD

**Issue by DoggoOfSpeed** [via-browser/Via#153]
In-app icons are inconsistent like these ones for history:
![diff1](https://user-images.githubusercontent.com/28051112/37598459-ed040424-2b8a-11e8-8dd5-9741ba34ab68.png)
And these ones for bookmarks:
![dif2](https://user-images.githubusercontent.com/28051112/37598492-04d76ce4-2b8b-11e8-8b21-96c784519c6a.png)
By removing one of the bookmark's icons you could make it more consistent and free up a few kb. (I get that the history icon is used in other places.)

**Comment by tuyafeng** [comment]
The icons used in bookmarks and history pages are drawn dynamically by css. In fact, this does not affect the application size. At the same time, these icons cannot be used by the application, and the icons on the web page cannot use the resources in the application.
