### ISSUE TITLE
Expand/shrink textboxes

### ISSUE THREAD

**Issue by DoggoOfSpeed** [via-browser/Via#155]
Hi! Right now the text in the menu cuts off in many languages. Maybe you could expand the text boxes as shown below? (Red=current textbox. Black=Better textbox)
![text](https://user-images.githubusercontent.com/28051112/37603309-f4bd57ae-2b96-11e8-95d7-4e7e0a1a4a01.png)
The text overlaps with the button in this place (at least in Lithuanian):
![screenshot_20180319-170404](https://user-images.githubusercontent.com/28051112/37603656-c12c2388-2b97-11e8-8e71-86fe6a94a947.png)
![screenshot_20180319-170255](https://user-images.githubusercontent.com/28051112/37603671-c9ab6ae6-2b97-11e8-8509-7b23b38d840f.png)

**Comment by tuyafeng** [comment]
Sorry, I saw this issue so late, I will fix it in the next version(3.9.9).
