### ISSUE TITLE
Open Previous Tabs WITHOUT Prompt

### ISSUE THREAD

**Issue by pidus** [via-browser/Via#158]
Via prompts user to open tabs that were open before closing the browser. It would be better if we could get an option in the settings so it could be set as a default action with NO prompt.

**Comment by ChuckyOtaku** [comment]
An option like this does exist, although I am not sure if was implemented before or after this  post by Pidus. Closing issue.

[screenshot_20190204-222846](https://user-images.githubusercontent.com/30413457/52251689-5b32b500-28cc-11e9-81c6-c3ec47c30bc7.png)

![screenshot_20190204-222842](https://user-images.githubusercontent.com/30413457/52251690-5bcb4b80-28cc-11e9-84a1-f1ead5194242.png)
