### ISSUE TITLE
根据域名变换ua

### ISSUE THREAD

**Issue by scskarsper** [via-browser/Via#166]
和广告过滤功能类似，通过匹配域名变换useragent。通过该规则来设置某个网站的显示类型。（如wap版百度/桌面版百度。以及百度网盘等）

**Comment by tuyafeng** [comment]
在 3.9.8 的版本之后，Via 已经可以针对特定站点进行单独设置，在浏览过程中点击左上角放大镜或盾牌图标可以看到。
