### ISSUE TITLE
禁止写入剪切板

### ISSUE THREAD

**Issue by mr-cn** [via-browser/Via#167]
垃圾网站喜欢偷偷写入支付宝的红包到剪切板
在发现这种行为时可以增加一个提示，由用户选择是否写入剪切板
就像网页启动app时一样

**Comment by tuyafeng** [comment]
很遗憾，webview 暂时不提供相应的接口，如果需要实现禁止网页写入剪贴板内容，可能只能在离开 Via 的时候清空剪贴板了，但是这并不是一个好的解决办法。
