### ISSUE TITLE
ViaBrowser已成为魔趣内置默认浏览器。

### ISSUE THREAD

**Issue by martincz** [via-browser/Via#168]
ViaBrowser的作者，您好！
我是魔趣开源项目的马丁龙猪，魔趣ROM是一个基于Android二次开发的第三方ROM。
我们致力于在不破坏原生风格的前提下，加入一些易于使用的本地化功能，让原生系统更好用。

在过去，我曾偏执的认为每一个系统内置的应用都应该是开源的、便于定制做本地化改动的。
因为预制第三方应用可能存在种种不可控因素和风险。（例如一些商业应用）
然而在最近，经过深思熟虑，我改变了这一想法。

我们没有精力、更没有能力面面俱到，对系统中每一个类型的应用作出改变。
让一些必不可少、却体验差劲的应用存在于系统中是可耻的，这会给玩机者带来麻烦。
经过考察，我认为浏览器是最优先可以作出变化的，并且魔趣的众多用户都很青睐ViaBrowser。

接下来，魔趣会将7.1和8.1版本上的默认浏览器更换为ViaBrowser。
同时，我们也希望能够为ViaBrowser的发展贡献一份力所能及的力量。
我们看到ViaBrowser的多语言是直接通过Github来管理的。
接下来，魔趣会将ViaBrowser的语言文件导入到crowdin上，利用魔趣的全球用户优势，为ViaBrowser提供很好的多语言支持。
如果可能，我们还希望未来能够做更多！

**Comment by LakorTi** [comment]
感谢认可，非常感谢魔趣的开明，我也很乐意 Via 浏览器能成为魔趣内置应用变更的先行者。PR 已合并，十分感谢魔趣为 Via 浏览器的国际化做出的贡献。

**Comment by LakorTi** [comment]
Via 浏览器的多语言版本为 GooglePlay 版本，包名是：mark.via.gp。望知晓。

**Comment by martincz** [comment]
感谢告知，我们会定期更新内置的VIA版本。
Github每天的邮件太多，所以方才注意到。
我看到到目前又有不少来自其它贡献者的新翻译提交，我会很快导入到crowdin上并准备下一次提交。

**Comment by jsbeyond** [comment]
Via浏览器真心不错
