### ISSUE TITLE
表单和桌面快捷方式

### ISSUE THREAD

**Issue by Sciroccogti** [via-browser/Via#170]
表单自动填充功能是不是暂时不支持？（还是说需要怎样的设置？）
还有就是，当前版本似乎找不到把网页固定到桌面的入口了？
感谢开发者！

**Comment by tuyafeng** [comment]
自动填充可以通过 android 的自动填充服务来实现。至于把网页添加到桌面，因为 android 碎片化的原因这个功能表现并不一致，已被移除。
