### ISSUE TITLE
是否能開發浮動視窗功能

### ISSUE THREAD

**Issue by omarco9476** [via-browser/Via#182]
感謝開發出小巧又功能強大的瀏覽器，很喜歡這款app，也時常使用它。
請問是否能開發浮動視窗功能？可自訂視窗大小、可以浮動在別的app之上，這樣查詢資料就很方便。感謝

**Comment by neilr27** [comment]
Sent from Mail for Windows 10

From: omarco9476
Sent: Thursday, June 21, 2018 11:02 PM
To: LakorTi/Via
Cc: Subscribed
Subject: [LakorTi/Via] 是否能開發浮動視窗功能 (#182)

感謝開發出小巧又功能強大的瀏覽器，很喜歡這款app，也時常使用它。
請問是否能開發浮動視窗功能？可自訂視窗大小、可以浮動在別的app之上，這樣查詢資料就很方便。感謝

**Comment by tuyafeng** [comment]
建议还是通过分屏来实现这样的需求吧，悬浮窗的限制过多，很多功能会受到限制。
