### ISSUE TITLE
启动恢复标签页不能恢复到最后状态

### ISSUE THREAD

**Issue by laerhu** [via-browser/Via#185]
差别
1. 标签页内容：自动恢复到了最后一次浏览需要回退才能到达的页面，例如最后在看Twitter，恢复的却是之前的知乎；
2. 标签页数量：关闭之前有5个，启动恢复之后却是7个，多出了上次打开时关闭的2个标签页

场景：浏览器重度用户，用网页代替app浏览常用网站：hupu、zhihu、YouTube、Twitter……

**Comment by tuyafeng** [comment]
目前 Via 仍然是只能记录住最后未关闭标签的链接，标签详细的信息暂未记录（例如浏览进度，是否是活跃标签）。这确实也存在问题，之后会考虑存储详细信息。
