### ISSUE TITLE
希望能加入inspect element功能

### ISSUE THREAD

**Issue by xiaoas** [via-browser/Via#188]
可能有点难度...但实在太方便了
现在的划广告不是很好用
另外能不能分域名给权限 不要JavaScript一关全关了这种

**Comment by tuyafeng** [comment]
检查元素这个功能暂时不考虑在移动端实现。现在 js 已经允许针对特定域名的开启或关闭。在浏览某个网站时，可以点击地址栏左侧放大镜或小盾牌图标进行针对站点的特定设置。
