### ISSUE TITLE
Swiping navigation bar

### ISSUE THREAD

**Issue by motfis** [via-browser/Via#197]
In the past, I set the swiping gesture in the navigation bar, e.g. to switch tab/back/forward. It is stop working in the latest version.
Also I cannot find the setting to modify it.
Please bring back this feature.
![screenshot_20180801-101248_via](https://user-images.githubusercontent.com/8572695/43495915-8c9695e8-9575-11e8-8d19-cf67094b3e79.jpg)

**Comment by kairusds** [comment]
@LakorTi

**Comment by PINCHO93** [comment]
Really hope they bring this back.

**Comment by filnirv** [comment]
+1

**Comment by motfis** [comment]
Will you bring this feature back?
I really miss this feature. many people too, I think

**Comment by GiovanniCarrozza** [comment]
+1

**Comment by tuyafeng** [comment]
This gesture has been removed and will not be added because it conflicts with some features.
