### ISSUE TITLE
Adding/converting a script to work in Via.

### ISSUE THREAD

**Issue by dajcou** [via-browser/Via#198]
Hi. I'm trying to add/convert this firefox script (javascript): https://github.com/mozilla/video-bg-play
so it works on the Via browser script section but I'm unsure of what needs to be done. The script allows youtube/vimeo videos to be played in the background on firefox mobile or while the screen is off. I assume this script could work on Via too. Can someone help convert the script so it will work on Via? It would be a nice addition.

**Comment by kairusds** [comment]
@dajcou It says that it only works in Firefox, not sure if it'll work on Via because the app uses Android System WebView as a base for rendering webpages.

**Comment by dajcou** [comment]
@kairusds It's just a small javascript code that perhaps could be adapted to work with Android webview? 

`'use strict';

// Page Visibility API
Object.defineProperties(document.wrappedJSObject,
  { 'hidden': {value: false}, 'visibilityState': {value: 'visible'} });

window.addEventListener(
  'visibilitychange', evt => evt.stopImmediatePropagation(), true);

// Fullscreen API
window.addEventListener('fullscreenchange', evt => {
  Object.defineProperties(document.wrappedJSObject,
    { 'fullscreenEnabled': {value: true},
      'fullscreen': {value: true},
      'fullscreenElement': {value: document.fullscreenElement.wrappedJSObject}});
  window.addEventListener(
    'fullscreenchange', evt => evt.stopImmediatePropagation(), true);
}, { capture: true, once: true });`

**Comment by bryanjhv** [comment]
I think it's not possible to do that, because (I think) Via executes scripts after the page was completely loaded (i.e. HTML is fetched, CSS is rendered, JS is executed), and the script you're trying to import overrides some HTML5 APIs to do work before the page is loaded.

**Comment by tuyafeng** [comment]
The javascript executed is similar to the js executed in Chrome/Firefox/Others console. After the console test is completed, you should compress the js into one line and copied to Via.

**Comment by N00B2** [comment]
Did this work?
