### ISSUE TITLE
Via description in Google play store

### ISSUE THREAD

**Issue by DoggoOfSpeed** [via-browser/Via#200]
So the Via description in the Google play store has some problems. Right now it goes like this:

✔ Quiet Browser
Via browser won’t push news and other things to you. No bother to your android devices.
✔ Mini Browser
Via browser use much less memory usage on your android devices. Keep your android devices as fast as new.
✔ Lite Browser
Via browser is designed for Minimalism. Best choice for geek user and who enjoy lite products.
✔ Customized Browser
You can easily customize Via browser. This is your own web browser. Best android browser for you to design your own homepage.
✔ Fastest Browser
Via browser is smooth for most android device. And we optimized a lot for fast browse. 

We hope you could enjoy your smooth and fresh browse time. That is what we are following.
Here are some features of Via web browser.
►Fast as lightning
This fast include the speed of open app and exit. Also include the fast speed of browse webs. Give your android phone fast-moving speed . Enjoy your fast web browse.
►Light but more
All the design is light and lite. All the experiences are light. If you enjoy the light browser , you got to love this one . Enjoy your light web browse time.
►Mini on android
The tiny apk. help save the memory of android device. Mini size also help android device smooth than ever. Enjoy your smooth web browse time.
►Best for Geek
Efficient is especially important. And the lite interface give you a fresh feel all the time. Enjoy your fresh and efficient web browse time.

Here are some functions of Via browser
• Date saving
• Customize 
• Ad block
• Privacy Protect
• Bookmarks
• Adds-on
• Night-mode
• Computer – mode
• Translate
• Find in page
• Search engine switch
• Web page save
• Intelligence picture show
• Free to design you homepage
Via Browser Product Concept
The main line of Via browser is geek. Make hard things simple.
Via browser pay attention to experience of browse. Fresh and lite. Every android phone can keep Via browser well in hand because of its mini size and memory usage.
Via browser have huge ability. Via browser have all formal function and advanced function such as web page code, weblog and more.
In a word , Make hard things simple.
Welcome to your feedback. Enjoy your time with Via Browser. Share Via Browser with others if you like .

And the problems are:
Poor Grammar
The description is too big
Repeats itself
Uses Emojis
Your target demographic are geeks. And it is OK, but you need to focus on the majority. (I'm not against geeks btw. In fact I am a geek myself)

Here is my version:

Quiet
Via won’t push news and other things to you that flood the notification bar.

Efficient
Via browser use way less RAM. This keeps your android devices as fast as new.

Customizable
You can easily customize Via. This is your own web browser, so make it look yours.

One of the fastest browsers. Ever.
Via browser is fast and can handle for a ton of browsing. It's just fast.

Small
It is tiny, this will leave you space for more apps and games.

Ad blocker
We hate those nasty ads. So let's remove them.

We listen to your feedback. Enjoy your time with Via. Share Via Browser with others if you like it.

**Comment by Vv2233Bb** [comment]
The same could go for your title. Here is the current one:
Via Browser - Fast & Light - Geek Best Choice

Here is my version:
Via Browser - Fast, Light & Customizable

**Comment by tuyafeng** [comment]
Thank you for your help.
