### ISSUE TITLE
Bug: Mark Ad doesn't work. 

### ISSUE THREAD

**Issue by dajcou** [via-browser/Via#201]
When I long press an ad on a website and click "Mark Ad" nothing happens. The AD still appears and nothing gets registered in the Mark Ad section under General setting.

**Comment by kairusds** [comment]
@dajcou Maybe the site renders an ad element and changes the id of it everytime you reload/enter it.

**Comment by kairusds** [comment]
@dajcou Like how Pixiv renders ads with different ad element id's

**Comment by dajcou** [comment]
@kairusds  uBlock Origin gets rid of all youtube ads and all other ads I know of in Chrome/Firefox/Opera so perhaps the list they use called EASY LIST can be added to the Via Browser? Link: https://easylist.to/easylist/easylist.txt  I see no ads whatsoever due to that list which seems to be better than what the Via Browser currently uses.

**Comment by tuyafeng** [comment]
Sometimes, the ad elements are random, in this case, you can not mark the ad currently. I would consider supporting easylist if possible.
