### ISSUE TITLE
能否详细介绍下自定义添加广告标记的规则编写格式？

### ISSUE THREAD

**Issue by danishevskiyigor2** [via-browser/Via#207]
【<div id="_kp6aukwnz6s】

想过滤这类DiV，但是id内容一直在变，只有最前面的_不变，所以标记为#_*，但无法过滤。是不是不支持通配符。

**Comment by 14725** [comment]
这不好说，，，
看样子，是个css选择器，，，
div[id^=_]
看看有没有用。

**Comment by tuyafeng** [comment]
目前只支持标准的 css 选择器，不支持通配符，建议优先考虑域名拦截来从根源阻止掉广告的加载。可以通过「菜单-工具-网络日志」拦截或放行相应规则。
