### ISSUE TITLE
[建议] 广告标记增加通过hosts文件批量导入域名列表

### ISSUE THREAD

**Issue by changxinjie** [via-browser/Via#208]
通过hosts文件批量导入的屏蔽的域名

**Comment by changxinjie** [comment]
没有root的手机无法修改操作系统hosts文件

**Comment by tuyafeng** [comment]
不知现在是否还有这个困惑，其实不是引用的系统 hosts，而是下载目录的一个 hosts.txt 文件，可以打开「菜单 - 工具 - 网络日志」，页面上方有完善的提示，同时也可以在日志页面通过长按任意条目直接拦截或放行。
