### ISSUE TITLE
[建议]能否适配锤子的TNT

### ISSUE THREAD

**Issue by skating507** [via-browser/Via#212]
现在适配TNT的浏览器不多，能否适配一下TNT呢

**Comment by tuyafeng** [comment]
Via 是严格按照 android 规范开发的，支持分屏和各类可扩展的属性，且目前为平板设备也做了优化，按理来说可以直接使用。同时我也没看到 TNT 的官方适配文档，猜测应该还是根据 android 的一些特性扩展的。
