### ISSUE TITLE
home page(speed dial) bug

### ISSUE THREAD

**Issue by kae-sakura** [via-browser/Via#230]
If make home page item from Bookmark Folder, can't delete this item

1) Make Bookmark and Folder 
2) Bookmarks>Open Folder
3) Long tap "..." and select "add home page"
4) success bookmark in homepage, but this item can't delete....
![screenshot_2018-09-29-23-34-25](https://user-images.githubusercontent.com/25323495/46247073-222b9500-c441-11e8-86f7-b87c2e7d9013.png)
![screenshot_2018-09-29-23-34-33](https://user-images.githubusercontent.com/25323495/46247074-22c42b80-c441-11e8-8171-e1311573ba04.png)

**Comment by tuyafeng** [comment]
Sorry for replying so late. It's really a long-term mistake. The next version(3.9.9) will fix this problem.
