### ISSUE TITLE
Please make two string name

### ISSUE THREAD

**Issue by kae-sakura** [via-browser/Via#231]
This string name is only one.
string name = "ui_simple" Simple
but this having difference UI

can make two string name?
example "Arrange above" & "Arrange under"
![screenshot_2018-09-30-00-01-20](https://user-images.githubusercontent.com/25323495/46247380-7a649600-c445-11e8-93cd-e8b8fb677006.png)

**Comment by Vv2233Bb** [comment]
Ikr? It could Be  "Simple (Bottom)" and  "Simple (Top)"

**Comment by tuyafeng** [comment]
Sorry for replying so late. Current version 3.9.9 has fixed this.
