### ISSUE TITLE
安卓版本3.4.0无法安装 “下载管理、二维码”插件

### ISSUE THREAD

**Issue by stdupanda** [via-browser/Via#240]
选择安装二维码和下载管理插件后就跳转到了应用市场，提示未收录改应用。

机型小米3C, miui9

**Comment by zo-shin** [comment]
小米应用商店会拦截某些软件下载网站的访问，强行转向自己的应用商店程序。此问题与via无关，请向小米公司投诉。

**Comment by stdupanda** [comment]
@zo-shin 您好能提供一下包括二维码扫描、下载管理插件的apk包吗？这两个功能太常用了

**Comment by zo-shin** [comment]
下载管理 [](https://soft.shouji.com.cn/down/26837.html)
二维码扫描 [](https://www.coolapk.com/apk/mark.qrcode)

**Comment by tuyafeng** [comment]
感谢 @zo-shin ，上面回复得很全面。
