### ISSUE TITLE
Question about UserScript  ?

### ISSUE THREAD

**Issue by mikhoul** [via-browser/Via#245]
Does it support TamperMonke/Greasemonkey API syntax ? 🤔

Also I really like if you can add a basic script editor in the Script section we could write/modify  Script directly from the browser.

Regards :octocat:

**Comment by tuyafeng** [comment]
The script function is currently only used as a supplement. The interface currently provided by webview is weak, and TamperMonke/Greasemonkey API is currently not supported.
