### ISSUE TITLE
【Feature Request】分享到微信朋友圈

### ISSUE THREAD

**Issue by highwindmx** [via-browser/Via#259]
![8d2cc9d20710afa63e0c061de94158b3](https://user-images.githubusercontent.com/6413481/49281933-d04ace00-f4c8-11e8-91fa-836f8497e629.jpg)

使用的是华为Mate20,EMUI 9.0.0.157，无法使用分享按钮弹出后系统分享模块进行微信朋友圈的分享，希望能够提供解析并分享到朋友圈的功能咯。非常感谢。

**Comment by tuyafeng** [comment]
暂时不考虑。
