### ISSUE TITLE
【Feature Request】提供打开收藏夹文件夹下所有连接的功能

### ISSUE THREAD

**Issue by highwindmx** [via-browser/Via#260]
既然设计了收藏夹的文件夹，那么还是希望能够 添加一下打开文件夹内所有链接的功能吧。

**Comment by LakorTi** [comment]
这个...很常用吗？什么情况下需要打开一个收藏夹内的所有书签呢？

**Comment by highwindmx** [comment]
> 
> 
> 这个...很常用吗？什么情况下需要打开一个收藏夹内的所有书签呢？

谢谢开发的大大啊，主要是有不少网站每次会去查新，需要一个个点总归麻烦，想到既然把他们放在一个文件夹下，那直接一并打开岂不是很方便咯。
