### ISSUE TITLE
Emoji support

### ISSUE THREAD

**Issue by mstfelq** [via-browser/Via#263]
Hello,
Thank you for this great browser. The problem that I'm facing lately is rendering some emojis as boxes. Not all of the emojis are supported to be rendered properly.

**Comment by LakorTi** [comment]
Is that emoji does not show in web page or something else?

**Comment by pthfdr-42** [comment]
Well, Android already has fonts to render emoji: `/system/fonts/NotoColorEmoji.ttf`, so it is a problem of your OS.
Also, if you want to render all emoji, Via have to embed an emoji font, which adds too much bloat.
Last but not least, emoji is the bane of intelligence. I removed that font as soon as I flashed my phone so I don't see those bullshit.
