### ISSUE TITLE
Article Title copy while Sharing

### ISSUE THREAD

**Issue by DOFfactory** [via-browser/Via#273]
When sharing a link of a webpage - article from the browser to email app (e.g. Gmail), the link gets copied to the content of the email, but the Title of the article is not copied to the subject. Would it be possible to implement this please?

**Comment by wowpaladin111** [comment]
It's a very important feature and most popular behavior of browsers. Please support it. Thanks.

**Comment by tuyafeng** [comment]
I have always felt tangled about sharing with or without a title. At present, it is to take care of some apps to handle links directly, so there is no title.
