### ISSUE TITLE
homepage出现无法处理的空白块

### ISSUE THREAD

**Issue by zbutfly** [via-browser/Via#274]
地址栏输入加一个地址为 https://aaa.bbb.com#hash 样的url并进入，注意#前没有/，会自动加这个#前的/。
然后放入bookmarks，edit该bookmark去掉#前的/保存，点击可正常访问，但再次edit，title/url均为空白。
然后将该bookmark放入homepage，变成一个空白块且无法编辑/删除。edit这个空白块发现title/url均为空白。给他一个title/url，会多出一个新的块，空白块不变。

这应该是个合法的url。估计哪个正则写得太紧了吧。

**Comment by tuyafeng** [comment]
合法的 url 应该是 https://aaa.bbb.com/#hash 。这个斜杠是必须的。
