### ISSUE TITLE
Bug: Displays password as plain text on Basic HTTP Authentication Pages

### ISSUE THREAD

**Issue by 1nsp1r3rnzt** [via-browser/Via#275]
The web pages with basic HTTP authentication displays password field as plain text. The server used is Nginx.
[This article](https://www.digitalocean.com/community/tutorials/how-to-set-up-basic-http-authentication-with-nginx-on-ubuntu-14-04) describes how to setup HTTP authentication for reproduction. 

Here is a screenshot from Via browser
![image](https://user-images.githubusercontent.com/7430699/49773400-f4738f80-fcbe-11e8-89fd-a215d04b57bb.png)
It is a security risk for users as password in plain field is remembered by the keyboard software for autocompletion. 

Here is a screenshot from InBrowser which displays password field correctly
![image](https://user-images.githubusercontent.com/7430699/49773417-01907e80-fcbf-11e8-9d8c-7603c6a8a49f.png)

**Comment by tuyafeng** [comment]
I will fix it in the next version(3.9.9).
