### ISSUE TITLE
UI Mode Simple 2 shows empty top bar

### ISSUE THREAD

**Issue by zilexa** [via-browser/Via#282]
Note: To prevent confusion, please rename the UI Modes. 2 modes have the same name: Simple. Also the name does not reflect their function.

Simple 2 shows a bottom address bar with 2 buttons and a menu button. When switching to Simple 2, there is an empty top bar shown. It is just a bar with nothing, colors change per website. Seems like a minor bug.

To get rid of it: disable Autohide and enable it again. Now, even if the bottom bar is shown, the empty top bar will be gone.

**Comment by Vv2233Bb** [comment]
That bar is broken tbh. If you try to type something in, the suggestions get covered by the keyboard.

**Comment by tuyafeng** [comment]
So sorry for my late reply. After a long time, many features have been changed. If there are still problems, please reopen the issue.
