### ISSUE TITLE
Feature request: share link

### ISSUE THREAD

**Issue by acroobat** [via-browser/Via#283]
It would be nice to add "share link" on selection in context menu.

**Comment by Vv2233Bb** [comment]
This feature exists, but it is called "Share". Just find it.

**Comment by Vv2233Bb** [comment]
It already exists. It is called share. You can find it in next to "add bookmarks" and below "night mode"

**Comment by acroobat** [comment]
No, I mean "Open in Background" "Open in New Tab" "Copy link". Share link is needed here.

**Comment by Vv2233Bb** [comment]
What about copy/paste?

**Comment by acroobat** [comment]
Thats ok but less convenient than just "Share link".

**Comment by Vv2233Bb** [comment]
But how often do you think you will use it?

**Comment by Vv2233Bb** [comment]
Also you can just open the link and press the share button.

**Comment by Vv2233Bb** [comment]
What about copy/paste?

**Comment by tuyafeng** [comment]
Just copy/paste it.
