### ISSUE TITLE
problem with opening a site made with javascript

### ISSUE THREAD

**Issue by ddesp** [via-browser/Via#285]
First, thank you for this great light browser. I have problems opening this particular site: [sofia.mpass.bg/bg](https://sofia.mpass.bg/bg) This is a portal for buying tickets through internet. Via loads the site content which is seen in Network log, but  depicts a blank page. It  should look this way:
![screenshot_2018-12-21](https://user-images.githubusercontent.com/46048483/50342645-96e80a00-052c-11e9-9fe1-88b29fffb9e6.png)
 Chrome, however, opens it correctly. As i can see from the source the page is generated by javascript. Javascript is enabled in Via. I have tried to change user agent to chrome, IE, Safari, but without luck.

**Comment by Vv2233Bb** [comment]
It works well for me

**Comment by ddesp** [comment]
I also use default user anent. All items in advanced settings are enabled. Could it depend on Android version (mine is 4.4.2)?  I am using MIUI, and it interesting that Xbrouser also doesn't open this site.

**Comment by Vv2233Bb** [comment]
I am on galaxy s4. Android 9.0. Also what is your Via version?

**Comment by ddesp** [comment]
My Via is ver. 3.5.1

**Comment by Vv2233Bb** [comment]
Well. Download Via from google play store. Might help (for me it works on 3.5.1 and 3.5.0

**Comment by tuyafeng** [comment]
So sorry for my late reply. After a long time, many features have been changed. If there are still problems, please reopen the issue.
