### ISSUE TITLE
Feature request clear search suggestion

### ISSUE THREAD

**Issue by 0ANIMEFREAK0** [via-browser/Via#286]
can u add a option to clear 
Search suggestions i cant clear it normally like i did it on chrome
on clear data on exit it clears my login information i tried it with 
forms data but it also clears my login information 
i just want my search suggestion to delete not my login information

i added a screenshot what i mean by  search suggestion
![img_20181109_041937](https://user-images.githubusercontent.com/35454710/50377511-f76c6980-0648-11e9-9278-030eb36277e0.jpg)

**Comment by 0ANIMEFREAK0** [comment]
i don't this will take this much time?
or u didn't what i am saying?

**Comment by tuyafeng** [comment]
You can clear the form data here: Settings - General - Clear Data.
