### ISSUE TITLE
[Feature Request] Add "Google NCR" to  Default Search Engine

### ISSUE THREAD

**Issue by Lythed** [via-browser/Via#291]
Already tried to add Google NCR by Custom URL but, I was not able to get it working.

Should be a good option to add. Im pretty bored to get my research in Dutch. :(

**Comment by Vv2233Bb** [comment]
What url did you put in?

**Comment by Lythed** [comment]
This one `https://www.google.com/search?q=%s&pws=0&gl=us&gws_rd=cr`

**Comment by Vv2233Bb** [comment]
Works well for me🙄

**Comment by Lythed** [comment]
Pretty weird, for me, the search is broken. For example when I try to type "Github" in the search bar, I got "%s" in the result. (and there is a contry redirect)

**Comment by tuyafeng** [comment]
Use `https://www.google.com/search?pws=0&gl=us&gws_rd=cr&q=`.
