### ISSUE TITLE
Feature Request: Mute Site

### ISSUE THREAD

**Issue by itzXian** [via-browser/Via#300]
Is it possible to add the __Mute Site__ feature in Via Browser?
Like Chrome ↓
![Chrome](https://raw.githubusercontent.com/xixian2106/site/imgs/Screenshot_20190104-231432_Chrome.png)

**Comment by siddhpant** [comment]
Why though, you can just change tabs and the video/sound stops.

Also, remember that this browser is lightweight.

**Comment by xixian2106** [comment]
1. I want to keep visiting a site without any sound from that site.

2. I always knew Via was a lightweight browser but that doesn't mean it has no any feature.
> Even Via has the** Network Log** feature, which is not available in most other browsers, even if they are larger than the Via.

Does adding this feature destroy its light weight?

Or it's impossible to add the **Mute Site** feature?

**This indeed is my wayward request** but please give me a clear answer, thanks!

**Comment by tuyafeng** [comment]
Sorry, webview does not have mute function. Currently, we can only mute the volume of webview by turning the phone volume to zero, but I know this is not what you want.

**Comment by itzXian** [comment]
> Sorry, webview does not have mute function. Currently, we can only mute the volume of webview by turning the phone volume to zero, but I know this is not what you want.

I see. thanks for the reply anyway.
