### ISSUE TITLE
[Feature Request] Ability to set region

### ISSUE THREAD

**Issue by KenJ45** [via-browser/Via#310]
It seems that some sites think I'm in China while using this browser. I'm in the USA. Wondering if there could be a setting to change broadcasted region manually.

**Comment by tuyafeng** [comment]
Can you give me an example of the site?

**Comment by KenJ45** [comment]
Oof, this was more than a year ago, but I THINK it was the search engines like google or bing seemed to think I was in China...

**Comment by tuyafeng** [comment]
Okay, I will check the search engine.
