### ISSUE TITLE
[Feature Request] Back and Forward buttons in menu while in Simple UI

### ISSUE THREAD

**Issue by KenJ45** [via-browser/Via#311]
I really like the UI "Simple" (the second one that puts the url bar on the bottom of the screen, maybe you should call them "Simple Top" and "Simple Bottom" ) but right now there's no way to navigate forward a page. I think when you touch the 3 lines on the bottom right the back and forward buttons should be in there. I know you can go back with the Android back key, that's what I use, but it would be weird to only have the forward button there on its own, that's why I suggest just having both...

**Comment by tuyafeng** [comment]
It can now be replaced by gestures. In addition, if the screen of your phone is large enough, you will get all the buttons visible in the op-bar.
