### ISSUE TITLE
Feature Request: Redirect to Default App instead of download

### ISSUE THREAD

**Issue by yoy232** [via-browser/Via#324]
It will be very helpful when the browser pop-up (for example when I click on video stream on the web page) the default app which is associated with respective MIME type (video player). When browser only download the playlist file, user must then search it in download directory and then open it in videoplayer app.

**Comment by yoy232** [comment]
...

**Comment by yoy232** [comment]
...

**Comment by tuyafeng** [comment]
Now you can play web videos on the resource sniffing page through third-party applications. Just press and hold an item in that page.
