### ISSUE TITLE
Latest version crashes, cookies wiped; Incognito confirmation

### ISSUE THREAD

**Issue by siddhpant** [via-browser/Via#326]
Version 3.5.8 crashed 2-3 times and my cookies are wiped (I am logged out of all websites!)

Also what's with the incognito mode? I like the way I can enable it, but it gets accidentally enabled, so can you put one confirmation dialogue for it? Also, it seems to save all the form data and cookies from incognito.

**Comment by tuyafeng** [comment]
It does not record browsing history when you are in incognito mode. As for cookie and formdata, they will still be saved.

**Comment by siddhpant** [comment]
Umm that literally defeats some of the main features of incognito.

**Comment by tuyafeng** [comment]
Yes, the current incognito mode is quite weak.
