### ISSUE TITLE
刷新失效，返回手势触发多标签页切换等bug

### ISSUE THREAD

**Issue by xwysun** [via-browser/Via#327]
1、via开启一段时间之后，刷新按钮失效和下拉刷新手势失效，刷新或者重新打开之前的网页会直接从cache读取，没有从网络更新最新内容。微博H5网页下很明显。
2、开启2个或者多个标签页的时候，多次右滑返回偶尔会触发标签页的切换。

**Comment by better-edgar** [comment]
同样遇到问题1

**Comment by tuyafeng** [comment]
我这边测试没发现诶，可以提供一个测试用例吗？

**Comment by tuyafeng** [comment]
抱歉。这个是因为之前的一个设定导致的问题，目前已经解决。
