### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by fcwys** [via-browser/Via#330]
1、书签支持多级目录和批量管理；
2、支持收藏书签时可选收藏到书签还是主页图标；
3、支持工具栏顺序自定义；
4、集成二维码扫描；
5、支持输入法增强栏；
6、布局设置为传统时主页图标显示为正方形而非长方形。
希望via更好！

**Comment by tuyafeng** [comment]
1. 这个会考虑支持；
2. 这个目前已经可以选择了；
3. 这个不考虑；
4. 暂时还不考虑；
5. 好提议；
6. 这个无所谓吧。
