### ISSUE TITLE
Feature request: Block pop ups more aggressively

### ISSUE THREAD

**Issue by siddhpant** [via-browser/Via#335]
Can you make blocking pop ups more aggressive, because even after enabling the option I get redirected to pop ups many a times!

I like the confirmation system, so can you make it aggressive please or like, ask every time a window tries to open? This should not be default but opt-in.

**Comment by 3xploiton3** [comment]
Need this too

**Comment by tuyafeng** [comment]
Can you give me an example of a website that abuses pop-ups?

**Comment by siddhpant** [comment]
Some short link websites, I guess? This issue is a year old and I forgot which was the troublesome website.

**Comment by tuyafeng** [comment]
Sorry for replying so late. I will close the issue. If you still have questions, you can reopen this issue at any time.
