### ISSUE TITLE
Multiline captions in the menu

### ISSUE THREAD

**Issue by ujos** [via-browser/Via#360]
Captions of some buttons in the Tools menu do not fit on the screen and are cut. Please find screenshot attached. 

Could you please wrap long captions. 

![20190507_093413](https://user-images.githubusercontent.com/70940/57281879-28a37e80-70ac-11e9-83d7-b92d242c3b14.jpg)

**Comment by tuyafeng** [comment]
Although it ’s a bit weird to say so, I think the two-line labels are not pretty.
