### ISSUE TITLE
Add the support of the scanning of  QR code

### ISSUE THREAD

**Issue by yunnysunny** [via-browser/Via#368]
QR scanning is an important function of a browser, so I think it a necessary for via too.

**Comment by pthfdr-42** [comment]
Just use a [third-party one](https://play.google.com/store/apps/details?id=com.blogspot.aeioulabs.barcode) and click on the link.

**Comment by stevenfelix505** [comment]
https://play.google.com/store/apps/details?id=mark.qrcode

**Comment by tuyafeng** [comment]
Install [qrcode extension](https://play.google.com/store/apps/details?id=mark.qrcode).
