### ISSUE TITLE
在魅族老webview环境下h5定位不可用

### ISSUE THREAD

**Issue by zzxjl1** [via-browser/Via#371]
webview版本:Mozilla/5.0 (Linux; Android 5.1; M571C Build/LMY47D; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.147 Mobile Safari/537.36/

一个很老的问题，最近开发遇到了，发现via也同样存在，完全不报错(js和log)，onGeolocationPermissionsShowPrompt也不被调用，目前还没有找到解决办法，装chrome则一切正常。

**Comment by tuyafeng** [comment]
定位需要先启用「设置 - 隐私 - 允许站点访问地理位置」，之后会弹出相应的地址请求弹窗，但，需要注意的是，这并不会让网站获取到位置信息，我猜测是 webview 接口的设定使然，因为我在另一台华为设备上测试时，其可以正确获取位置。出于这种迷惑性，我默认关闭了「允许站点访问地理位置」。
