### ISSUE TITLE
[Minor Bug] 'Simple' option shows up twice on 'Operation Bar UI Mode'

### ISSUE THREAD

**Issue by AndhikaWB** [via-browser/Via#373]
Not sure if they are actually different, never tried it. See screenshot.
![20190622_193220](https://user-images.githubusercontent.com/17119394/59963961-7c670b80-9524-11e9-8bf8-355ba12c0ab5.jpg)

**Comment by tuyafeng** [comment]
I will fix it in the next version(3.9.9).
