### ISSUE TITLE
查看网页源代码会丢失数据！

### ISSUE THREAD

**Issue by HaydenHu** [via-browser/Via#379]
查看网页源代码我用过Chrome、fireFox、x浏览器，带最好用的就是VIA了，html代码经格式化，结构清晰，非常好用！

但是有些网站的部分网页会出现，源码只能获取到部分，并不完整，不知道为什么，同一网页其他浏览器则获取完整。
比如:https://www.xiaobiquge.com 
这个网站的搜索结果目录部分的源码就会丢失无法获取！

**不知道哪里出了问题，希望下一个版本能修复！**

**Comment by HaydenHu** [comment]
也就是via不能查看网页动态加载的数据！

**Comment by tuyafeng** [comment]
确实，Via 当前的网页源码功能只能查看网页最初的源代码，之后通过 ajax 或其它形式加载的数据不会展示在源代码，因为当前也只是简单的调用了一个接口，这个功能目前只适合处理一点简单的需要看到源代码的需求。
