### ISSUE TITLE
Dark mode whitout forced image brightness dimming, Bug?, Feature request!

### ISSUE THREAD

**Issue by ShadowMaster85** [via-browser/Via#380]
I am using the latest available version of Via browser, when activating the night mode and dark mode (by long press on the night mode button) the brightness of all images on the pages are automatically dimmed, it's a Bug? if it's not a Bug it's possible to separate the image brightness dim function from the dark mode? so the Dark mode can be activated without having all the images brightness automatically dimmed down and have a separate option to dim the brightness? Thank you!

**Comment by tuyafeng** [comment]
When you are in the dark mode, in addition to the webpage will force the dark color, the picture will be darkened to adapt to the night. This is a feature.
