### ISSUE TITLE
Downloader Problem

### ISSUE THREAD

**Issue by Nayon889** [via-browser/Via#407]
Hey developers in Via browser 3.9.4 version not supporting Download Manager... I want to use Adm pro download manager but there showing error...Please fix this as early as possible...

**Comment by stevenfelix505** [comment]
Try Different Download Manager(s)

**Comment by marcdw1289** [comment]
@Nayon889 
You should mention what version of ADM Pro you're using. ADM Pro works just fine with Via. Version 7.6 though. If you're using ADM v8.x then that might explain the error. The original ADM disappeared from the Play Store. This new version 8 has a different package name and probably unrecognized by Via.
Just a guess. Again, ADM Pro up to v7.6 is good to go (for me).

**Comment by tuyafeng** [comment]
Thx @marcdw1289 , I don’t know that adm changed the package name, and I will follow up this change in the app.
