### ISSUE TITLE
Panes not scrolling

### ISSUE THREAD

**Issue by ghost** [via-browser/Via#41]
Logitech Media Server does not scroll, neither the left or right pane - screenshot & code attached.
Opera Mini has same problem, Opera does it correctly.
Ole

Screenshot:
![logitech media server-1496770076870](https://user-images.githubusercontent.com/25547766/26843336-351cd8de-4af0-11e7-8c7a-482e966c9d95.png)

Code saved in Via browser:
[lms-code-from-via.txt](https://github.com/LakorTi/Via/files/1060460/lms-code-from-via.txt)

**Comment by tuyafeng** [comment]
So sorry for my late reply. After a long time, many features have been changed. If there are still problems, please reopen the issue.
