### ISSUE TITLE
请教一下: 关于冻结应用 边缘 

### ISSUE THREAD

**Issue by aklivecai** [via-browser/Via#415]
请问还更新么? 很好用的软件, 新版1.2版有个 问题

同时禁用多个app的时候,只有第一次的禁用是成功,其它的都没有禁用成功

需要完全退出,再打开app 才能禁用下一个app

1.0版本没有这个问题

打搅了

**Comment by tuyafeng** [comment]
还会更新，最近我正在计划重构一个魔盒。不出意外的话下个月应该会发布。

**Comment by tuyafeng** [comment]
提前占个位置，之后会开源出来。欢迎提前关注 [Watt](https://github.com/tuyafeng/Watt)。
