### ISSUE TITLE
小米平板4 VIA浏览器无退出按键

### ISSUE THREAD

**Issue by londbell** [via-browser/Via#417]
![QQ20191224-0](https://user-images.githubusercontent.com/7590762/71395239-17fe4380-2650-11ea-92c8-c5c0660afcec.png)
应用布局为“自动”
使用手机上云同步过来的设置，也不会出现退出按钮
导致使用的时候要不停返回-返回-返回按键，把所有网页历史清空才能退出app

**Comment by tuyafeng** [comment]
建议直接从多任务划掉，Via 遵循[安卓绿色应用公约](https://green-android.org/app-convention.html)，也通过了华为绿色应用认证，从多任务划掉本质上和直接按返回键或应用内退出并无区别。
