### ISSUE TITLE
手机上设置了书签同步的账号密码，在http://via.oktutu.com/zh-hans/cloud/这个地址老是说账号不存在

### ISSUE THREAD

**Issue by kingo132** [via-browser/Via#418]
手机上设置了书签同步的账号密码，在http://via.oktutu.com/zh-hans/cloud/这个地址老是说账号不存在，这是为啥？

**Comment by kingo132** [comment]
换了个用户名注册就好了，真神奇

**Comment by tuyafeng** [comment]
目前云同步有两个在线站点，分别对应两个服务器。推荐优先使用国内服务器，速度更快。

国内：https://app.viayoo.com/cloud
国际：http://via.oktutu.com/cloud
