### ISSUE TITLE
导入书签功能有问题

### ISSUE THREAD

**Issue by an15m** [via-browser/Via#420]
今天从chrome导出书签，然后导入，由于我的书签比较多，而且有多级目录，虽然显示导入成功，但是实际上一团乱，多级目录的直接显示的是最内层目录，外层目录都没了，而且导入的不全

**Comment by tuyafeng** [comment]
目前 Via 还不支持多级目录，所以多级目录会直接把目录导入到根目录下。在支持书签多级目录前，问题可能不会得到解决。还是建议移动设备书签按需添加。
