### ISSUE TITLE
申请出一份脚本开发规范

### ISSUE THREAD

**Issue by HerbertHe** [via-browser/Via#458]
我跟着`via-app.cn`的指南写脚本，在chrome里面和usb调试工具都没有任何问题，但是不能在浏览器里面执行，不是play的版本。

**Comment by HerbertHe** [comment]
申请了邀请码，也没有得到回复。

**Comment by tuyafeng** [comment]
via-app.cn 目前是第三方爱好者在维护，脚本就是常规的 js，但是受限于移动设备和 webview 接口的孱弱，脚本可能在网页加载前或网页加载中运行。

**Comment by HerbertHe** [comment]
为了避免这个问题，确实去做了脚本一次性运行，但是还是没能找出问题所在，分号对执行还有影响吗。。

**Comment by tuyafeng** [comment]
有的，建议脚本测试完成后通过[相关工具](https://tool.lu/js/)压缩成一行js。

**Comment by HerbertHe** [comment]
嗷嗷好的，还是希望在有些特别注意的地方可以出一个开发规范，非常乐意做一些自定义的扩展

**Comment by tuyafeng** [comment]
好，之后其实更考虑直接接入油猴脚本规则。
