### ISSUE TITLE
广告拦截

### ISSUE THREAD

**Issue by undefined303** [via-browser/Via#459]
广告拦截建议弄个拦截网址，就是某些广告网址标记拦截以后就不可以访问了，或访问时会提醒，然后确认了再继续，管理可以在广告拦截里面编辑或删除，。。有的广告网址点进去就出不来了。除非禁用JavaScript。。

**Comment by tuyafeng** [comment]
善用网络日志（菜单-工具-网络日志）。长按任意日志页面的条目可以自行选择拦截与否。
