### ISSUE TITLE
Little bit more space for "Toolbar" at bottom

### ISSUE THREAD

**Issue by th23x** [via-browser/Via#82]
Is it possible to give the toolbar at the bottom a little bit more space (height)?

With Android devices having a physical back key, you mistakenly quite often hit this instead of the tabs button...

If not as a default, can you maybe make this adjustable by user via the settings?

**Comment by jiht594** [comment]
这个建议很好，另外希望可以调整工具栏。工具中的功能现在需要多次点击。最右边的按钮（三形状这个按钮），自定义是不是好一点，或者弹出的变成3行。因为现在也是3行，第三行只有关闭浏览器和收起菜单两个按钮，第三行左边是空白的。

不过我说的改法也有缺点。希望作者再接再厉。非常喜欢这个浏览器。

**Comment by tuyafeng** [comment]
Is the width of the bottom bar not enough now? I want the web part to occupy as much space as possible.

**Comment by th23x** [comment]
Agree with giving the content as much space as possible.

And today nearly all phones moved away from physical back buttons (and more gestures are used) the hight is fine for me.
