### ISSUE TITLE
Videos are purple & green (HW acceleration Toggle)

### ISSUE THREAD

**Issue by Ashraf284** [via-browser/Via#86]
Recently switched to VIA and found this problem. Videos are green & purple colored.

I know it's related to HW acceleration. 
I also found this problem on chrome & fixed it by going to chrome://flags and disabling "HW accelerated video decode".

As much as I know there are no option like chrome://flags in VIA. If there is please let me know. 

And if there isn't,
Please add a toggle for HW acceleration in the settings menu.
Thank you in advance.

**Comment by tuyafeng** [comment]
I think this is a firmware issue, maybe you should try to update the firmware.
