### ISSUE TITLE
Bring bacj

### ISSUE THREAD

**Issue by AnkushKakne** [via-browser/Via#96]
There is an option in via browser version 3.1.5 that would let users customize menu items. Users could drag and sort menu items as per their preferences. But in the latest version you removed this option that is making via browser hard to use.

I always save webpages and create shortcut of webpages on home screen for reading them later.
And I often use other useful commands too.

In version 3.1.5 I could easily save page, create shortcut, check history, switch to desktop site by going to menu and choosing a command (I had arrenged all those commands as per my preference) but now I have to go to menu, click on tools, check where the specific command is and click on it that is hard, time consuming and annoying. So please I request you to bring back that customize menu items option (drag and sort menu items) back.

Also this latest version (3.2.0) 
saves pages titles with symbols in between, these titles had spaces in previous version but now they have '+ %' signs, thats annoying.

Please I request you to fix this issue and bring the customize menu items (drag and sort menu items) back. Both issues are important to solve making this browser best.

**Comment by tuyafeng** [comment]
The feature of adding web pages to the desktop has been deprecated. Saving web pages can now customize the title.
